source("R/build_truth_set.R")
source("R/amputate_data.R")

data_frame <- readRDS("data/analysis_frame.rds")
col_missingness <- colSums(is.na(select(data_frame, all_of(c("AGEY1X", "SEX", "REGIONY1", "POVCATY1", "INSCOVY1", "RTHLTH1", "DIABDXY1_M18", "TOTEXPY1", "TOTEXPY2")))))
truth <- build_truth_set(data_frame)

amp_mcar <- amputate_data(truth$true_data, "MCAR")
amp_mar <- amputate_data(truth$true_data, "MAR")
amp_mnar <- amputate_data(truth$true_data, "MNAR")
cat("# rows before filtering out NA: ", nrow(data_frame), "\n")
cat("NA missingness of data by column: ", col_missingness, "\n")
cat("# rows after filtering out NA: ", nrow(truth$true_data), "\n")
cat("MCAR missing rate: ", mean(is.na(amp_mcar$TOTEXPY2)), "\n")
cat("MAR missing rate: ", mean(is.na(amp_mar$TOTEXPY2)), "\n")
cat("MNAR missing rate: ", mean(is.na(amp_mnar$TOTEXPY2)), "\n")
cat("MCAR observed totexpy2 mean: ", mean(amp_mcar$TOTEXPY2, na.rm = TRUE), "\n")
cat("MAR observed totexpy2 mean: ", mean(amp_mar$TOTEXPY2,  na.rm = TRUE), "\n")
cat("MNAR observed totexpy2 mean: ", mean(amp_mnar$TOTEXPY2, na.rm = TRUE),"\n")
cat("True observed totexpy2 mean: ", truth$true_mean_exp, "\n")